version: '2'

services:
  gitbucket:
    build: .
    image: k-sh/gitbucket:4.9
    ports:
    - "8080:8080"
    - "29418:29418"
    volumes:
    - ./data:/opt/gitbucket/data
    restart: unless-stopped
